### ISSUE TITLE
Location/ World

### ISSUE THREAD

**Issue by ghost** [mattjrumble/crop-circle-tracker-plugin#1]
Hi, Just downloaded this plugin & think it would be a useful feature to sort by worlds instead of location. its very hard to go through locations to find the world i'm on. Maybe a search bar for worlds to help? thanks :)

**Comment by mattjrumble** [comment]
What's the use case? I think most people pick the crop circle location first, then just hop to a high-likelihood world. When would it be useful to find the location for your current world?

**Comment by ghost** [comment]
might be very niche but i was doing the new forestry update where people gather in one world and friendschat to call out where the new events spawn, and inbetween callouts i was catching eclectic implings for clues, the puro wheat boost really sped up the process. so in summary it would be for people that can’t hop due to other activities/ folks that would rather stay one world, clan world or maybe ping related, or for efficiency players that don't want to be hopping around every 30 minutes when the boost runs out or scrolling through a bunch of locations to find out where to go next. thanks for getting back to me anyway, understand if its not feasible. :)

**Comment by mattjrumble** [comment]
Thanks for the explanation, I'm trying to work out what the right fix is.

Is the main issue that you might miss callouts/you have to leave the clan chat for a bit when hopping worlds? Or is it that actually hopping worlds is annoying to do (I know that the double-clicking to hop worlds isn't great sometimes)?

I still would've thought it'd be easier and quicker to pick a location, hop to another world, then hop back once you're in Puro Puro - rather than travelling to whichever of the 18 locations the crop circle is at in your world?

I don't think I'd have the time to make new UI components like a nice search bar - it took me an embarrassingly long time to make the current UI. I could do something like highlight the locations in the drop-down menu if there's a chance the crop circle is at that location in the current world. Would that do the job?
